name: dailythingspro
description: "Maintain your life"

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"
dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    flutter_animate: ^4.5.0
    page_transition: ^2.1.0
    shared_preferences: ^2.2.3
    flutter_riverpod: ^2.5.1
    audioplayers: ^6.0.0
    day_night_time_picker: ^1.3.1
    flutter_local_notifications: ^17.1.2
    timezone: ^0.9.3
    permission_handler: ^11.3.1
    intl: ^0.19.0
    sqflite: ^2.3.3+1
    vibration: ^1.8.4
    flutter_hooks: ^0.20.5
    url_launcher: ^6.2.6
    flutter_heatmap_calendar: ^1.0.5
    flutter_slidable: ^3.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    riverpod_annotation: ^2.3.5
    riverpod_lint: ^2.3.10
    custom_lint: ^0.6.4

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - lib/assets/common/
        - assets/audio/
        - lib/assets/main/
        - lib/assets/glyphs/

    fonts:
        - family: Cabinet
          fonts:
              - asset: lib/fonts/reg.otf
              - asset: lib/fonts/med.otf
                weight: 500
              - asset: lib/fonts/bold.otf
                weight: 700
              - asset: lib/fonts/black.otf
                weight: 800
